# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinte', '0002_auto_20160718_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme_name',
            field=models.CharField(max_length=400),
        ),
    ]
